/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MicroLending } from './MicroLending.js';
export * as factories from './factories/index.js';
export { MicroLending__factory } from './factories/MicroLending__factory.js';