/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MicroLending {
      
    export type LoanStruct = {id: BigNumberish, borrower: AddressLike, lender: AddressLike, amount: BigNumberish, interestRate: BigNumberish, duration: BigNumberish, dueDate: BigNumberish, repaidAmount: BigNumberish, status: BigNumberish, riskScore: BigNumberish, createdAt: BigNumberish, purpose: string}

    export type LoanStructOutput = [id: bigint, borrower: string, lender: string, amount: bigint, interestRate: bigint, duration: bigint, dueDate: bigint, repaidAmount: bigint, status: bigint, riskScore: bigint, createdAt: bigint, purpose: string] & {id: bigint, borrower: string, lender: string, amount: bigint, interestRate: bigint, duration: bigint, dueDate: bigint, repaidAmount: bigint, status: bigint, riskScore: bigint, createdAt: bigint, purpose: string }
  
    }

  export interface MicroLendingInterface extends Interface {
    getFunction(nameOrSignature: "borrowerLoans" | "calculateRepaymentAmount" | "calculateRiskScore" | "cancelLoan" | "fundLoan" | "getBorrowerLoans" | "getLenderLoans" | "getLoan" | "getTotalLoans" | "lenderLoans" | "loans" | "markAsDefaulted" | "owner" | "platformFee" | "renounceOwnership" | "repayLoan" | "requestLoan" | "totalPlatformFees" | "transferOwnership" | "updatePlatformFee" | "userReputation" | "withdrawPlatformFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LoanCancelled" | "LoanDefaulted" | "LoanFunded" | "LoanRepaid" | "LoanRequested" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'borrowerLoans', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateRepaymentAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateRiskScore', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBorrowerLoans', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getLenderLoans', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalLoans', values?: undefined): string;
encodeFunctionData(functionFragment: 'lenderLoans', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'loans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markAsDefaulted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestLoan', values: [BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'totalPlatformFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'userReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawPlatformFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'borrowerLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateRepaymentAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateRiskScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowerLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lenderLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAsDefaulted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPlatformFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPlatformFees', data: BytesLike): Result;
  }

  
    export namespace LoanCancelledEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
      export type OutputTuple = [loanId: bigint, borrower: string];
      export interface OutputObject {loanId: bigint, borrower: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanDefaultedEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
      export type OutputTuple = [loanId: bigint, borrower: string];
      export interface OutputObject {loanId: bigint, borrower: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanFundedEvent {
      export type InputTuple = [loanId: BigNumberish, lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, lender: string, amount: bigint];
      export interface OutputObject {loanId: bigint, lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, amount: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRequestedEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, amount: BigNumberish, interestRate: BigNumberish, duration: BigNumberish, riskScore: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, amount: bigint, interestRate: bigint, duration: bigint, riskScore: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, amount: bigint, interestRate: bigint, duration: bigint, riskScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MicroLending extends BaseContract {
    
    connect(runner?: ContractRunner | null): MicroLending;
    waitForDeployment(): Promise<this>;

    interface: MicroLendingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    borrowerLoans: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateRepaymentAmount: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateRiskScore: TypedContractMethod<
      [_borrower: AddressLike, _amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getBorrowerLoans: TypedContractMethod<
      [_borrower: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getLenderLoans: TypedContractMethod<
      [_lender: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [MicroLending.LoanStructOutput],
      'view'
    >
    

    
    getTotalLoans: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lenderLoans: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    loans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {id: bigint, borrower: string, lender: string, amount: bigint, interestRate: bigint, duration: bigint, dueDate: bigint, repaidAmount: bigint, status: bigint, riskScore: bigint, createdAt: bigint, purpose: string }],
      'view'
    >
    

    
    markAsDefaulted: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repayLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    requestLoan: TypedContractMethod<
      [_amount: BigNumberish, _interestRate: BigNumberish, _duration: BigNumberish, _purpose: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    totalPlatformFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlatformFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    userReputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawPlatformFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'borrowerLoans'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateRepaymentAmount'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateRiskScore'): TypedContractMethod<
      [_borrower: AddressLike, _amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getBorrowerLoans'): TypedContractMethod<
      [_borrower: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderLoans'): TypedContractMethod<
      [_lender: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [MicroLending.LoanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalLoans'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lenderLoans'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'loans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {id: bigint, borrower: string, lender: string, amount: bigint, interestRate: bigint, duration: bigint, dueDate: bigint, repaidAmount: bigint, status: bigint, riskScore: bigint, createdAt: bigint, purpose: string }],
      'view'
    >;
getFunction(nameOrSignature: 'markAsDefaulted'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'requestLoan'): TypedContractMethod<
      [_amount: BigNumberish, _interestRate: BigNumberish, _duration: BigNumberish, _purpose: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalPlatformFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlatformFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userReputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawPlatformFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LoanCancelled'): TypedContractEvent<LoanCancelledEvent.InputTuple, LoanCancelledEvent.OutputTuple, LoanCancelledEvent.OutputObject>;
getEvent(key: 'LoanDefaulted'): TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
getEvent(key: 'LoanFunded'): TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'LoanRequested'): TypedContractEvent<LoanRequestedEvent.InputTuple, LoanRequestedEvent.OutputTuple, LoanRequestedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'LoanCancelled(uint256,address)': TypedContractEvent<LoanCancelledEvent.InputTuple, LoanCancelledEvent.OutputTuple, LoanCancelledEvent.OutputObject>;
      LoanCancelled: TypedContractEvent<LoanCancelledEvent.InputTuple, LoanCancelledEvent.OutputTuple, LoanCancelledEvent.OutputObject>;
    

      'LoanDefaulted(uint256,address)': TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
      LoanDefaulted: TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
    

      'LoanFunded(uint256,address,uint256)': TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
      LoanFunded: TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
    

      'LoanRepaid(uint256,address,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'LoanRequested(uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<LoanRequestedEvent.InputTuple, LoanRequestedEvent.OutputTuple, LoanRequestedEvent.OutputObject>;
      LoanRequested: TypedContractEvent<LoanRequestedEvent.InputTuple, LoanRequestedEvent.OutputTuple, LoanRequestedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }